---
- name: "Laboratorio de facts"
  hosts: nodo1
  tasks:
    - name: "Imprimer todos los facts"
      debug:
        var: ansible_facts

    - name: "Crear el fichero datos_nombre_nodo"
      file:
        path: /tmp/datos_nombre_nodo.txt
        state: touch
        mode: 0655

    - name: "Inserción de datos en el fichero"
      lineinfile:
        path: /tmp/datos_nombre_nodo.txt
        line: "El nodo {{ ansible_facts['hostname'] }} tiene IP {{ ansible_facts['default_ipv4']['address'] }}"
        create: yes

    - name: "Dispositivo de almacenamiento"
      lineinfile:
        path: /tmp/datos_nombre_nodo.txt
        line: "disco {{ ansible.facts['device']['sda']['size'] }}"

    - name: "Particionado disco añadido New 2GB partition" 
      parted:
        device: /dev/sdb
        number: 1
        state: present
        part_end: 2GB

    - name: "Creates a volume group" 
      lvg:
        vg: vg_prueba
        pvs: /dev/sda1
        pesize: 32

    - name: "Create a logical volume of 2GB" 
      lvol:
        vg: vg_prueba
        lv: lv_prueba
        size: 2gb

    - name: "Create an XFS filesystem"
      filesystem:
        fstype: xfs
        dev: /dev/sdb1

    - name: "Mount device with ID" 
      mount:
        path: /data
        src: UUID=a8063676-44dd-409a-b584-68be2c9f5570 
        fstype: xfs
        state: present


      

